//! Released migrations are immutable — including their comments.
//!
//! sqlx records a checksum of every applied migration file in `_sqlx_migrations`
//! and refuses to open a database whose file has since changed
//! (`migration N was previously applied but has been modified`). A one-word
//! comment edit to `0006_playback_sessions.sql` shipped in v1.0.0 and locked every
//! existing Ferrofin database out of the upgrade. This test pins the checksum of
//! every migration so that edit fails CI instead of a user's boot.
//!
//! Adding a migration: append its line by running
//! `FERROFIN_WRITE_MIGRATION_CHECKSUMS=1 cargo test -p ferrofin-db --test migration_immutability`
//! and commit the updated `tests/data/migration_checksums.txt`. Changing an existing
//! line is never right: write a new migration instead.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

static MIGRATOR: sqlx::migrate::Migrator = sqlx::migrate!("./migrations");

const PINNED: &str = "tests/data/migration_checksums.txt";

fn hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}

fn current() -> BTreeMap<i64, (String, String)> {
    MIGRATOR
        .iter()
        .map(|m| (m.version, (m.description.to_string(), hex(&m.checksum))))
        .collect()
}

fn render(map: &BTreeMap<i64, (String, String)>) -> String {
    let mut out = String::from(
        "# version  checksum (sqlx, sha-384 of the file)  description\n\
         # Generated by tests/migration_immutability.rs — append for a new migration, never edit a line.\n",
    );
    for (v, (desc, sum)) in map {
        let _ = writeln!(out, "{v:04}  {sum}  {desc}");
    }
    out
}

fn parse(text: &str) -> BTreeMap<i64, String> {
    text.lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .filter_map(|l| {
            let mut it = l.split_whitespace();
            let v = it.next()?.parse().ok()?;
            let sum = it.next()?.to_string();
            Some((v, sum))
        })
        .collect()
}

#[test]
fn released_migrations_have_not_changed() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(PINNED);
    let now = current();
    if std::env::var_os("FERROFIN_WRITE_MIGRATION_CHECKSUMS").is_some() {
        std::fs::write(&path, render(&now)).expect("write the pinned checksums");
        return;
    }
    let pinned =
        parse(&std::fs::read_to_string(&path).expect("tests/data/migration_checksums.txt exists"));
    let mut problems = Vec::new();
    for (v, (desc, sum)) in &now {
        match pinned.get(v) {
            None => problems.push(format!(
                "migration {v:04} ({desc}) is not pinned — append it with FERROFIN_WRITE_MIGRATION_CHECKSUMS=1"
            )),
            Some(p) if p != sum => problems.push(format!(
                "migration {v:04} ({desc}) CHANGED since it was released: a database that already applied it \
                 will refuse to open. Revert the file byte-for-byte and put the change in a NEW migration."
            )),
            Some(_) => {}
        }
    }
    for v in pinned.keys() {
        if !now.contains_key(v) {
            problems.push(format!(
                "pinned migration {v:04} no longer exists — released migrations are never removed"
            ));
        }
    }
    assert!(problems.is_empty(), "{}", problems.join("\n"));
}
