#!/usr/bin/env python3
"""Generate suite/registry.json — the single join key between parity and perf (Plan 6, M1/M3).

Every benchmark variant is a parameterization of one contract operation. This imports the
bench endpoint table (suite/perf/endpoints.py `ENDPOINTS` — plain data, no parsing) and the
vendored OpenAPI spec, and emits a registry keyed by operation ("GET /Items/Filters2") with
bench variants under it. Run once to (re)generate; the committed registry.json is the source
of truth after that (variant ids are permanent trend keys — see registry_selftest.py).
Re-running only adds newly-benched endpoints; it never rewrites existing variant ids, and it
preserves aliases.
"""
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENDPOINTS_PY = ROOT / "suite" / "perf" / "endpoints.py"
SPEC = next((ROOT / "contracts").glob("jellyfin-openapi-*.json"))
OUT = Path(__file__).resolve().parent / "registry.json"

# Bench context fields → OpenAPI path params. userId is always a query param in the bench
# set, so it never appears here; item ids are the only path templating we do.
PATH_VARS = {
    "{itemId}": "{itemId}",
    "{imageItemId}": "{itemId}",
    "{writeItemId}": "{itemId}",
    "{seriesId}": "{seriesId}",
    "{playlistId}": "{playlistId}",
    "{taskId}": "{taskId}",
    "{userId}": "{userId}",
    "{imageTag}": "{tag}",
}

# Variants whose concrete path carries a literal where the spec has a param (e.g. the image
# type "Primary" is the {imageType} path param). Map the derived op_path to the spec op_path.
OP_OVERRIDES = {
    "/Items/{itemId}/Images/Primary": "/Items/{itemId}/Images/{imageType}",
    "/Items/{itemId}/Images/Primary/0": "/Items/{itemId}/Images/{imageType}/{imageIndex}",
    "/Items/{itemId}/Images/Primary/0/{tag}/webp/300/450/0/0":
        "/Items/{itemId}/Images/{imageType}/{imageIndex}/{tag}/{format}/{maxWidth}/{maxHeight}"
        "/{percentPlayed}/{unplayedCount}",
    "/System/Configuration/encoding": "/System/Configuration/{key}",
}


def normalize(tmpl: str):
    """A bench path template → (op_path, query_params). '/Items/{itemId}?userId={userId}'
    → ('/Items/{itemId}', 'userId={userId}&...'). Context aliases ({imageItemId},
    {writeItemId}) collapse to the spec's path param; the query keeps its fields."""
    path, _, query = tmpl.partition("?")
    for ctx, spec in PATH_VARS.items():
        path = path.replace(ctx, spec)
    return path, query


def parse_endpoints():
    """(name, method, path-template) straight from suite/perf/endpoints.py —
    imported as data, so there is no line format or parsing convention to keep."""
    spec_mod = importlib.util.spec_from_file_location("bench_endpoints", ENDPOINTS_PY)
    mod = importlib.util.module_from_spec(spec_mod)
    spec_mod.loader.exec_module(mod)
    return [(e["name"], e["method"], e["path"]) for e in mod.ENDPOINTS]


def main():
    spec = json.loads(SPEC.read_text())
    paths = spec["paths"]

    def tag_for(op_path, method):
        node = paths.get(op_path, {}).get(method.lower(), {})
        tags = node.get("tags") or []
        return tags[0] if tags else "_untagged"

    # Preserve existing aliases if the registry already exists (re-gen is non-destructive).
    existing = {}
    if OUT.exists():
        for entry in json.loads(OUT.read_text())["operations"]:
            for v in entry["variants"]:
                existing[v["id"]] = v

    by_op, unmatched = {}, []
    for name, method, tmpl in parse_endpoints():
        op_path, query = normalize(tmpl)
        op_path = OP_OVERRIDES.get(op_path, op_path)
        opkey = f"{method} {op_path}"
        if op_path not in paths or method.lower() not in paths[op_path]:
            unmatched.append((name, opkey))
            continue
        variant = {"id": name, "params": query, "load": "default"}
        if name in existing and "was" in existing[name]:
            variant["was"] = existing[name]["was"]
        by_op.setdefault(opkey, {"op": opkey, "tag": tag_for(op_path, method), "variants": []})
        by_op[opkey]["variants"].append(variant)

    if unmatched:
        print("!! variants whose op is NOT in the vendored spec (fix normalize/spec):",
              file=sys.stderr)
        for name, opkey in unmatched:
            print(f"   {name:24} {opkey}", file=sys.stderr)
        sys.exit(1)

    registry = {
        "_comment": "Generated by suite/gen-registry.py. Keyed by contract operation; variant "
                    "ids are permanent trend keys — rename only via a variant 'was' alias.",
        "operations": sorted(by_op.values(), key=lambda e: e["op"]),
    }
    OUT.write_text(json.dumps(registry, indent=2) + "\n")
    nv = sum(len(e["variants"]) for e in by_op.values())
    print(f">> wrote {OUT.relative_to(ROOT)}: {len(by_op)} operations, {nv} variants")


if __name__ == "__main__":
    main()
