#!/usr/bin/env python3
"""Generate suite/registry.json — the single join key between parity and perf (Plan 6, M1/M3).

Every benchmark variant is a parameterization of one contract operation. This reads the
existing bench endpoint list (benchmark/bench-lib.js `ENDPOINTS`) and the vendored OpenAPI
spec, and emits a registry keyed by operation ("GET /Items/Filters2") with bench variants
under it. Run once to (re)generate; the committed registry.json is the source of truth after
that (variant ids are permanent trend keys — see registry_selftest.py). Re-running only adds
newly-benched endpoints; it never rewrites existing variant ids, and it preserves aliases.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCH_LIB = ROOT / "benchmark" / "bench-lib.js"
SPEC = next((ROOT / "contracts").glob("jellyfin-openapi-*.json"))
OUT = Path(__file__).resolve().parent / "registry.json"

# k6 template vars → OpenAPI path params. userId is always a query param in the bench set, so
# it never appears here; item ids are the only path templating we do.
PATH_VARS = {
    "c.itemId": "{itemId}",
    "c.imageItemId": "{itemId}",
    "c.writeItemId": "{itemId}",
    "c.seriesId": "{seriesId}",
    "c.playlistId": "{playlistId}",
    "c.taskId": "{taskId}",
    "c.userId": "{userId}",
    "c.imageTag": "{tag}",
}

# Variants whose concrete path carries a literal where the spec has a param (e.g. the image
# type "Primary" is the {imageType} path param). Map the derived op_path to the spec op_path.
OP_OVERRIDES = {
    "/Items/{itemId}/Images/Primary": "/Items/{itemId}/Images/{imageType}",
    "/Items/{itemId}/Images/Primary/0": "/Items/{itemId}/Images/{imageType}/{imageIndex}",
    "/Items/{itemId}/Images/Primary/0/{tag}/webp/300/450/0/0":
        "/Items/{itemId}/Images/{imageType}/{imageIndex}/{tag}/{format}/{maxWidth}/{maxHeight}"
        "/{percentPlayed}/{unplayedCount}",
    "/System/Configuration/encoding": "/System/Configuration/{key}",
}


def normalize(tmpl: str):
    """A bench path template → (op_path, query_params). '/Items/${c.itemId}?userId=${c.userId}'
    → ('/Items/{itemId}', 'userId={userId}&...')."""
    path, _, query = tmpl.partition("?")
    for js, spec in PATH_VARS.items():
        path = path.replace("${" + js + "}", spec)
    # Any remaining ${c.foo} in the path we couldn't map is a bug — surface it.
    query = re.sub(r"\$\{c\.(\w+)\}", lambda m: "{" + m.group(1) + "}", query)
    return path, query


def parse_endpoints():
    """Pull (name, method, path-template) out of the ENDPOINTS array in bench-lib.js.

    Parsed LINE-WISE (entries are one per line by convention, stated in bench-lib):
    a cross-entry regex with an optional `method:` group could otherwise swallow a
    neighboring entry's fields. `method` defaults to GET when absent.
    """
    text = BENCH_LIB.read_text()
    block = text[text.index("export const ENDPOINTS"):]
    block = block[:block.index("\n];")]
    out = []
    for line in block.splitlines():
        name = re.search(r"name:\s*'(\w+)'", line)
        path = re.search(r"path:\s*\([^)]*\)\s*=>\s*(`[^`]*`|'[^']*')", line)
        if not (name and path):
            continue
        method = re.search(r"method:\s*'(\w+)'", line)
        out.append((name.group(1), method.group(1) if method else "GET", path.group(1)[1:-1]))
    return out


def main():
    spec = json.loads(SPEC.read_text())
    paths = spec["paths"]

    def tag_for(op_path, method):
        node = paths.get(op_path, {}).get(method.lower(), {})
        tags = node.get("tags") or []
        return tags[0] if tags else "_untagged"

    # Preserve existing aliases if the registry already exists (re-gen is non-destructive).
    existing = {}
    if OUT.exists():
        for entry in json.loads(OUT.read_text())["operations"]:
            for v in entry["variants"]:
                existing[v["id"]] = v

    by_op, unmatched = {}, []
    for name, method, tmpl in parse_endpoints():
        op_path, query = normalize(tmpl)
        op_path = OP_OVERRIDES.get(op_path, op_path)
        opkey = f"{method} {op_path}"
        if op_path not in paths or method.lower() not in paths[op_path]:
            unmatched.append((name, opkey))
            continue
        variant = {"id": name, "params": query, "load": "default"}
        if name in existing and "was" in existing[name]:
            variant["was"] = existing[name]["was"]
        by_op.setdefault(opkey, {"op": opkey, "tag": tag_for(op_path, method), "variants": []})
        by_op[opkey]["variants"].append(variant)

    if unmatched:
        print("!! variants whose op is NOT in the vendored spec (fix normalize/spec):",
              file=sys.stderr)
        for name, opkey in unmatched:
            print(f"   {name:24} {opkey}", file=sys.stderr)
        sys.exit(1)

    registry = {
        "_comment": "Generated by suite/gen-registry.py. Keyed by contract operation; variant "
                    "ids are permanent trend keys — rename only via a variant 'was' alias.",
        "operations": sorted(by_op.values(), key=lambda e: e["op"]),
    }
    OUT.write_text(json.dumps(registry, indent=2) + "\n")
    nv = sum(len(e["variants"]) for e in by_op.values())
    print(f">> wrote {OUT.relative_to(ROOT)}: {len(by_op)} operations, {nv} variants")


if __name__ == "__main__":
    main()
