//! `TrickplayController` — scrubbing-preview playlists and tiles.
//!
//! Ports both of Jellyfin's `TrickplayController` routes:
//! - `GET /Videos/{itemId}/Trickplay/{width}/tiles.m3u8` — the HLS image-tiles
//!   playlist for a resolution (built from the stored trickplay metadata).
//! - `GET /Videos/{itemId}/Trickplay/{width}/{index}.jpg` — a single tile image
//!   file (served when present on disk).
//!
//! The `{index}.jpg` segment is normalized to a single `{index}` capture by the
//! router (the `.jpg` literal is dropped); the handler serves the on-disk tile
//! path resolved by the [`TrickplayManager`]. Tile *generation* is deferred (no
//! media encoder), so an item whose metadata exists but whose tiles were never
//! generated yields `404` for the image — matching the C# `File.Exists` gate.

use axum::Router;
use axum::extract::{Path, Query, Request, State};
use axum::http::header;
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use hermit_model::secret::Secret;
use uuid::Uuid;

use crate::auth::RequireAuth;
use crate::error::ApiError;
use crate::handlers::streaming::serve_static_file;
use crate::state::AppState;

/// Query parameters shared by the trickplay routes.
#[derive(Debug, Default, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct TrickplayQuery {
    /// Optional. The media version id, if using an alternate version.
    #[serde(default)]
    media_source_id: Option<Uuid>,
}

/// `GET /Videos/{itemId}/Trickplay/{width}/tiles.m3u8` — the tiles playlist.
///
/// Port of `TrickplayController.GetTrickplayHlsPlaylist`: builds the `.m3u8`
/// text for the resolution `width` (keyed on the `mediaSourceId` when supplied,
/// else the item id). Returns `404` when no trickplay metadata exists for that
/// resolution.
#[utoipa::path(
    get,
    path = "/Videos/{itemId}/Trickplay/{width}/tiles.m3u8",
    params(
        ("itemId" = String, Path, description = "The item id"),
        ("width" = i32, Path, description = "The width of a single tile"),
        ("mediaSourceId" = Option<String>, Query, description = "The media version id, if using an alternate version")
    ),
    responses(
        (status = 200, description = "Tiles playlist returned"),
        (status = 404, description = "Not found")
    ),
    tag = "hermit"
)]
async fn get_trickplay_hls_playlist(
    State(state): State<AppState>,
    RequireAuth(auth): RequireAuth,
    Path((item_id, width)): Path<(Uuid, i32)>,
    Query(query): Query<TrickplayQuery>,
) -> Result<Response, ApiError> {
    let source_id = query.media_source_id.unwrap_or(item_id);
    let playlist = state
        .trickplay
        .get_hls_playlist(source_id, width, auth.token.as_ref().map(Secret::expose))
        .await?;
    match playlist {
        Some(text) if !text.is_empty() => {
            Ok(([(header::CONTENT_TYPE, "application/x-mpegURL")], text).into_response())
        }
        _ => Err(ApiError::NotFound(format!(
            "no trickplay playlist for item {item_id} at width {width}"
        ))),
    }
}

/// `GET /Videos/{itemId}/Trickplay/{width}/{index}.jpg` — a tile image.
///
/// Port of `TrickplayController.GetTrickplayTileImage`: resolves the on-disk
/// tile path for the resolution + tile index (keyed on `mediaSourceId` when
/// supplied, else the item id) and serves the file with a
/// `Content-Disposition: attachment` header. Returns `404` when the resolution
/// is unknown or the tile file is absent (tiles are generated by the deferred
/// encoder).
///
/// The trailing `.jpg` literal is normalized away by the router, so `index` is
/// captured as a bare integer.
#[utoipa::path(
    get,
    path = "/Videos/{itemId}/Trickplay/{width}/{index}",
    params(
        ("itemId" = String, Path, description = "The item id"),
        ("width" = i32, Path, description = "The width of a single tile"),
        ("index" = i32, Path, description = "The index of the desired tile"),
        ("mediaSourceId" = Option<String>, Query, description = "The media version id, if using an alternate version")
    ),
    responses(
        (status = 200, description = "Tile image returned"),
        (status = 404, description = "Not found")
    ),
    tag = "hermit"
)]
async fn get_trickplay_tile_image(
    State(state): State<AppState>,
    RequireAuth(_auth): RequireAuth,
    Path((item_id, width, index)): Path<(Uuid, i32, i32)>,
    Query(query): Query<TrickplayQuery>,
    request: Request,
) -> Result<Response, ApiError> {
    let source_id = query.media_source_id.unwrap_or(item_id);
    let Some(path) = state
        .trickplay
        .get_trickplay_tile_path(source_id, width, index)
        .await?
    else {
        return Err(ApiError::NotFound(format!(
            "no trickplay tiles for item {item_id} at width {width}"
        )));
    };

    let mut response = serve_static_file(&path, request).await?;
    if let Ok(value) = header::HeaderValue::from_str("attachment") {
        response
            .headers_mut()
            .insert(header::CONTENT_DISPOSITION, value);
    }
    Ok(response)
}

/// Registers this controller's real routes onto `router`.
pub fn register(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/Videos/{itemId}/Trickplay/{width}/tiles.m3u8",
            get(get_trickplay_hls_playlist),
        )
        .route(
            "/Videos/{itemId}/Trickplay/{width}/{index}",
            get(get_trickplay_tile_image),
        )
}
