//! The vendored Jellyfin 10.11.8 route table — the authoritative client
//! contract. GENERATED from `tests/data/jellyfin-openapi-10.11.8.json`; do not
//! edit by hand. Each entry is a `(method, path)` pair exactly as it appears in
//! the spec (Jellyfin `{param}` placeholders preserved verbatim). The router and
//! the contract-superset test both consume this table.

/// Every `(method, path)` pair in the vendored Jellyfin OpenAPI spec.
///
/// 412 entries across 337 distinct paths. `method` is
/// lowercase (`get`/`post`/`delete`/`head`); `path` uses Jellyfin's
/// `{param}` placeholder syntax.
pub const VENDORED_ROUTES: &[(&str, &str)] = &[
    ("get", "/Albums/{itemId}/InstantMix"),
    ("get", "/Albums/{itemId}/Similar"),
    ("get", "/Artists"),
    ("get", "/Artists/AlbumArtists"),
    ("get", "/Artists/InstantMix"),
    ("get", "/Artists/{itemId}/InstantMix"),
    ("get", "/Artists/{itemId}/Similar"),
    ("get", "/Artists/{name}"),
    ("get", "/Artists/{name}/Images/{imageType}/{imageIndex}"),
    ("head", "/Artists/{name}/Images/{imageType}/{imageIndex}"),
    ("delete", "/Audio/{itemId}/Lyrics"),
    ("get", "/Audio/{itemId}/Lyrics"),
    ("post", "/Audio/{itemId}/Lyrics"),
    ("get", "/Audio/{itemId}/RemoteSearch/Lyrics"),
    ("post", "/Audio/{itemId}/RemoteSearch/Lyrics/{lyricId}"),
    ("get", "/Audio/{itemId}/hls/{segmentId}/stream.aac"),
    ("get", "/Audio/{itemId}/hls/{segmentId}/stream.mp3"),
    (
        "get",
        "/Audio/{itemId}/hls1/{playlistId}/{segmentId}.{container}",
    ),
    ("get", "/Audio/{itemId}/main.m3u8"),
    ("get", "/Audio/{itemId}/master.m3u8"),
    ("head", "/Audio/{itemId}/master.m3u8"),
    ("get", "/Audio/{itemId}/stream"),
    ("head", "/Audio/{itemId}/stream"),
    ("get", "/Audio/{itemId}/stream.{container}"),
    ("head", "/Audio/{itemId}/stream.{container}"),
    ("get", "/Audio/{itemId}/universal"),
    ("head", "/Audio/{itemId}/universal"),
    ("get", "/Auth/Keys"),
    ("post", "/Auth/Keys"),
    ("delete", "/Auth/Keys/{key}"),
    ("get", "/Auth/PasswordResetProviders"),
    ("get", "/Auth/Providers"),
    ("get", "/Backup"),
    ("post", "/Backup/Create"),
    ("get", "/Backup/Manifest"),
    ("post", "/Backup/Restore"),
    ("get", "/Branding/Configuration"),
    ("get", "/Branding/Css"),
    ("get", "/Branding/Css.css"),
    ("delete", "/Branding/Splashscreen"),
    ("get", "/Branding/Splashscreen"),
    ("post", "/Branding/Splashscreen"),
    ("get", "/Channels"),
    ("get", "/Channels/Features"),
    ("get", "/Channels/Items/Latest"),
    ("get", "/Channels/{channelId}/Features"),
    ("get", "/Channels/{channelId}/Items"),
    ("post", "/ClientLog/Document"),
    ("post", "/Collections"),
    ("delete", "/Collections/{collectionId}/Items"),
    ("post", "/Collections/{collectionId}/Items"),
    ("delete", "/Devices"),
    ("get", "/Devices"),
    ("get", "/Devices/Info"),
    ("get", "/Devices/Options"),
    ("post", "/Devices/Options"),
    ("get", "/DisplayPreferences/{displayPreferencesId}"),
    ("post", "/DisplayPreferences/{displayPreferencesId}"),
    ("get", "/Environment/DefaultDirectoryBrowser"),
    ("get", "/Environment/DirectoryContents"),
    ("get", "/Environment/Drives"),
    ("get", "/Environment/NetworkShares"),
    ("get", "/Environment/ParentPath"),
    ("post", "/Environment/ValidatePath"),
    ("get", "/Episode/{Id}/Timestamps"),
    ("post", "/Episode/{Id}/Timestamps"),
    ("get", "/Episode/{id}/IntroSkipperSegments"),
    ("get", "/FallbackFont/Fonts"),
    ("get", "/FallbackFont/Fonts/{name}"),
    ("post", "/FileTransformation/RegisterTransformation"),
    ("get", "/Genres"),
    ("get", "/Genres/{genreName}"),
    ("get", "/Genres/{name}/Images/{imageType}"),
    ("head", "/Genres/{name}/Images/{imageType}"),
    ("get", "/Genres/{name}/Images/{imageType}/{imageIndex}"),
    ("head", "/Genres/{name}/Images/{imageType}/{imageIndex}"),
    ("get", "/GetUtcTime"),
    ("get", "/IntroSkipper"),
    ("get", "/IntroSkipper/SupportBundle"),
    ("post", "/Intros/AnalyzerActions/UpdateSeason"),
    ("get", "/Intros/AnalyzerActions/{SeasonId}"),
    ("post", "/Intros/EraseTimestamps"),
    ("post", "/Intros/RebuildDatabase"),
    ("post", "/Intros/ScanSeason/{SeriesId}/{SeasonId}"),
    ("get", "/Intros/ScanStatus"),
    ("delete", "/Intros/Show/{SeriesId}/{SeasonId}"),
    ("get", "/Intros/Show/{SeriesId}/{SeasonId}"),
    ("delete", "/Items"),
    ("get", "/Items"),
    ("get", "/Items/Counts"),
    ("get", "/Items/Filters"),
    ("get", "/Items/Filters2"),
    ("get", "/Items/Latest"),
    ("post", "/Items/RemoteSearch/Apply/{itemId}"),
    ("post", "/Items/RemoteSearch/Book"),
    ("post", "/Items/RemoteSearch/BoxSet"),
    ("post", "/Items/RemoteSearch/Movie"),
    ("post", "/Items/RemoteSearch/MusicAlbum"),
    ("post", "/Items/RemoteSearch/MusicArtist"),
    ("post", "/Items/RemoteSearch/MusicVideo"),
    ("post", "/Items/RemoteSearch/Person"),
    ("post", "/Items/RemoteSearch/Series"),
    ("post", "/Items/RemoteSearch/Trailer"),
    ("get", "/Items/Root"),
    ("get", "/Items/Suggestions"),
    ("delete", "/Items/{itemId}"),
    ("get", "/Items/{itemId}"),
    ("post", "/Items/{itemId}"),
    ("get", "/Items/{itemId}/Ancestors"),
    ("post", "/Items/{itemId}/ContentType"),
    ("get", "/Items/{itemId}/CriticReviews"),
    ("get", "/Items/{itemId}/Download"),
    ("get", "/Items/{itemId}/ExternalIdInfos"),
    ("get", "/Items/{itemId}/File"),
    ("get", "/Items/{itemId}/Images"),
    ("delete", "/Items/{itemId}/Images/{imageType}"),
    ("get", "/Items/{itemId}/Images/{imageType}"),
    ("head", "/Items/{itemId}/Images/{imageType}"),
    ("post", "/Items/{itemId}/Images/{imageType}"),
    ("delete", "/Items/{itemId}/Images/{imageType}/{imageIndex}"),
    ("get", "/Items/{itemId}/Images/{imageType}/{imageIndex}"),
    ("head", "/Items/{itemId}/Images/{imageType}/{imageIndex}"),
    ("post", "/Items/{itemId}/Images/{imageType}/{imageIndex}"),
    (
        "post",
        "/Items/{itemId}/Images/{imageType}/{imageIndex}/Index",
    ),
    (
        "get",
        "/Items/{itemId}/Images/{imageType}/{imageIndex}/{tag}/{format}/{maxWidth}/{maxHeight}/{percentPlayed}/{unplayedCount}",
    ),
    (
        "head",
        "/Items/{itemId}/Images/{imageType}/{imageIndex}/{tag}/{format}/{maxWidth}/{maxHeight}/{percentPlayed}/{unplayedCount}",
    ),
    ("get", "/Items/{itemId}/InstantMix"),
    ("get", "/Items/{itemId}/Intros"),
    ("get", "/Items/{itemId}/LocalTrailers"),
    ("get", "/Items/{itemId}/MetadataEditor"),
    ("get", "/Items/{itemId}/PlaybackInfo"),
    ("post", "/Items/{itemId}/PlaybackInfo"),
    ("post", "/Items/{itemId}/Refresh"),
    ("get", "/Items/{itemId}/RemoteImages"),
    ("post", "/Items/{itemId}/RemoteImages/Download"),
    ("get", "/Items/{itemId}/RemoteImages/Providers"),
    ("get", "/Items/{itemId}/RemoteSearch/Subtitles/{language}"),
    (
        "post",
        "/Items/{itemId}/RemoteSearch/Subtitles/{subtitleId}",
    ),
    ("get", "/Items/{itemId}/Similar"),
    ("get", "/Items/{itemId}/SpecialFeatures"),
    ("get", "/Items/{itemId}/ThemeMedia"),
    ("get", "/Items/{itemId}/ThemeSongs"),
    ("get", "/Items/{itemId}/ThemeVideos"),
    ("post", "/Jellyfin.Plugin.OpenSubtitles/ValidateLoginInfo"),
    ("get", "/Libraries/AvailableOptions"),
    ("post", "/Library/Media/Updated"),
    ("get", "/Library/MediaFolders"),
    ("post", "/Library/Movies/Added"),
    ("post", "/Library/Movies/Updated"),
    ("get", "/Library/PhysicalPaths"),
    ("post", "/Library/Refresh"),
    ("post", "/Library/Series/Added"),
    ("post", "/Library/Series/Updated"),
    ("delete", "/Library/VirtualFolders"),
    ("get", "/Library/VirtualFolders"),
    ("post", "/Library/VirtualFolders"),
    ("post", "/Library/VirtualFolders/LibraryOptions"),
    ("post", "/Library/VirtualFolders/Name"),
    ("delete", "/Library/VirtualFolders/Paths"),
    ("post", "/Library/VirtualFolders/Paths"),
    ("post", "/Library/VirtualFolders/Paths/Update"),
    ("post", "/LiveStreams/Close"),
    ("post", "/LiveStreams/Open"),
    ("get", "/LiveTv/ChannelMappingOptions"),
    ("post", "/LiveTv/ChannelMappings"),
    ("get", "/LiveTv/Channels"),
    ("get", "/LiveTv/Channels/{channelId}"),
    ("get", "/LiveTv/GuideInfo"),
    ("get", "/LiveTv/Info"),
    ("delete", "/LiveTv/ListingProviders"),
    ("post", "/LiveTv/ListingProviders"),
    ("get", "/LiveTv/ListingProviders/Default"),
    ("get", "/LiveTv/ListingProviders/Lineups"),
    ("get", "/LiveTv/ListingProviders/SchedulesDirect/Countries"),
    ("get", "/LiveTv/LiveRecordings/{recordingId}/stream"),
    (
        "get",
        "/LiveTv/LiveStreamFiles/{streamId}/stream.{container}",
    ),
    ("get", "/LiveTv/Programs"),
    ("post", "/LiveTv/Programs"),
    ("get", "/LiveTv/Programs/Recommended"),
    ("get", "/LiveTv/Programs/{programId}"),
    ("get", "/LiveTv/Recordings"),
    ("get", "/LiveTv/Recordings/Folders"),
    ("get", "/LiveTv/Recordings/Groups"),
    ("get", "/LiveTv/Recordings/Groups/{groupId}"),
    ("get", "/LiveTv/Recordings/Series"),
    ("delete", "/LiveTv/Recordings/{recordingId}"),
    ("get", "/LiveTv/Recordings/{recordingId}"),
    ("get", "/LiveTv/SeriesTimers"),
    ("post", "/LiveTv/SeriesTimers"),
    ("delete", "/LiveTv/SeriesTimers/{timerId}"),
    ("get", "/LiveTv/SeriesTimers/{timerId}"),
    ("post", "/LiveTv/SeriesTimers/{timerId}"),
    ("get", "/LiveTv/Timers"),
    ("post", "/LiveTv/Timers"),
    ("get", "/LiveTv/Timers/Defaults"),
    ("delete", "/LiveTv/Timers/{timerId}"),
    ("get", "/LiveTv/Timers/{timerId}"),
    ("post", "/LiveTv/Timers/{timerId}"),
    ("delete", "/LiveTv/TunerHosts"),
    ("post", "/LiveTv/TunerHosts"),
    ("get", "/LiveTv/TunerHosts/Types"),
    ("get", "/LiveTv/Tuners/Discover"),
    ("get", "/LiveTv/Tuners/Discvover"),
    ("post", "/LiveTv/Tuners/{tunerId}/Reset"),
    ("get", "/Localization/Countries"),
    ("get", "/Localization/Cultures"),
    ("get", "/Localization/Options"),
    ("get", "/Localization/ParentalRatings"),
    ("get", "/MediaSegments/{itemId}"),
    ("get", "/MediaSegmentsApi"),
    ("post", "/MediaSegmentsApi/{itemId}"),
    ("delete", "/MediaSegmentsApi/{segmentId}"),
    ("post", "/MergeVersions/MergeEpisodes"),
    ("post", "/MergeVersions/MergeMovies"),
    ("post", "/MergeVersions/SplitEpisodes"),
    ("post", "/MergeVersions/SplitMovies"),
    ("get", "/Movies/Recommendations"),
    ("get", "/Movies/{itemId}/Similar"),
    ("get", "/MusicGenres"),
    ("get", "/MusicGenres/InstantMix"),
    ("get", "/MusicGenres/{genreName}"),
    ("get", "/MusicGenres/{name}/Images/{imageType}"),
    ("head", "/MusicGenres/{name}/Images/{imageType}"),
    ("get", "/MusicGenres/{name}/Images/{imageType}/{imageIndex}"),
    (
        "head",
        "/MusicGenres/{name}/Images/{imageType}/{imageIndex}",
    ),
    ("get", "/MusicGenres/{name}/InstantMix"),
    ("get", "/Packages"),
    ("post", "/Packages/Installed/{name}"),
    ("delete", "/Packages/Installing/{packageId}"),
    ("get", "/Packages/{name}"),
    ("get", "/Persons"),
    ("get", "/Persons/{name}"),
    ("get", "/Persons/{name}/Images/{imageType}"),
    ("head", "/Persons/{name}/Images/{imageType}"),
    ("get", "/Persons/{name}/Images/{imageType}/{imageIndex}"),
    ("head", "/Persons/{name}/Images/{imageType}/{imageIndex}"),
    ("get", "/Playback/BitrateTest"),
    ("delete", "/PlayingItems/{itemId}"),
    ("post", "/PlayingItems/{itemId}"),
    ("post", "/PlayingItems/{itemId}/Progress"),
    ("post", "/Playlists"),
    ("get", "/Playlists/{itemId}/InstantMix"),
    ("get", "/Playlists/{playlistId}"),
    ("post", "/Playlists/{playlistId}"),
    ("delete", "/Playlists/{playlistId}/Items"),
    ("get", "/Playlists/{playlistId}/Items"),
    ("post", "/Playlists/{playlistId}/Items"),
    (
        "post",
        "/Playlists/{playlistId}/Items/{itemId}/Move/{newIndex}",
    ),
    ("get", "/Playlists/{playlistId}/Users"),
    ("delete", "/Playlists/{playlistId}/Users/{userId}"),
    ("get", "/Playlists/{playlistId}/Users/{userId}"),
    ("post", "/Playlists/{playlistId}/Users/{userId}"),
    ("get", "/Plugins"),
    ("delete", "/Plugins/{pluginId}"),
    ("get", "/Plugins/{pluginId}/Configuration"),
    ("post", "/Plugins/{pluginId}/Configuration"),
    ("post", "/Plugins/{pluginId}/Manifest"),
    ("delete", "/Plugins/{pluginId}/{version}"),
    ("post", "/Plugins/{pluginId}/{version}/Disable"),
    ("post", "/Plugins/{pluginId}/{version}/Enable"),
    ("get", "/Plugins/{pluginId}/{version}/Image"),
    ("get", "/Providers/Lyrics/{lyricId}"),
    ("get", "/Providers/Subtitles/Subtitles/{subtitleId}"),
    ("post", "/QuickConnect/Authorize"),
    ("get", "/QuickConnect/Connect"),
    ("get", "/QuickConnect/Enabled"),
    ("post", "/QuickConnect/Initiate"),
    ("get", "/Repositories"),
    ("post", "/Repositories"),
    ("get", "/ScheduledTasks"),
    ("delete", "/ScheduledTasks/Running/{taskId}"),
    ("post", "/ScheduledTasks/Running/{taskId}"),
    ("get", "/ScheduledTasks/{taskId}"),
    ("post", "/ScheduledTasks/{taskId}/Triggers"),
    ("get", "/Search/Hints"),
    ("get", "/Sessions"),
    ("post", "/Sessions/Capabilities"),
    ("post", "/Sessions/Capabilities/Full"),
    ("post", "/Sessions/Logout"),
    ("post", "/Sessions/Playing"),
    ("post", "/Sessions/Playing/Ping"),
    ("post", "/Sessions/Playing/Progress"),
    ("post", "/Sessions/Playing/Stopped"),
    ("post", "/Sessions/Viewing"),
    ("post", "/Sessions/{sessionId}/Command"),
    ("post", "/Sessions/{sessionId}/Command/{command}"),
    ("post", "/Sessions/{sessionId}/Message"),
    ("post", "/Sessions/{sessionId}/Playing"),
    ("post", "/Sessions/{sessionId}/Playing/{command}"),
    ("post", "/Sessions/{sessionId}/System/{command}"),
    ("delete", "/Sessions/{sessionId}/User/{userId}"),
    ("post", "/Sessions/{sessionId}/User/{userId}"),
    ("post", "/Sessions/{sessionId}/Viewing"),
    ("get", "/Shows/NextUp"),
    ("get", "/Shows/Upcoming"),
    ("get", "/Shows/{itemId}/Similar"),
    ("get", "/Shows/{seriesId}/Episodes"),
    ("get", "/Shows/{seriesId}/Seasons"),
    ("post", "/SkipButtonCss/InjectCss"),
    ("post", "/SkipButtonCss/UpdateSkipDuration"),
    ("get", "/Songs/{itemId}/InstantMix"),
    ("post", "/Startup/Complete"),
    ("get", "/Startup/Configuration"),
    ("post", "/Startup/Configuration"),
    ("get", "/Startup/FirstUser"),
    ("post", "/Startup/RemoteAccess"),
    ("get", "/Startup/User"),
    ("post", "/Startup/User"),
    ("get", "/Studios"),
    ("get", "/Studios/{name}"),
    ("get", "/Studios/{name}/Images/{imageType}"),
    ("head", "/Studios/{name}/Images/{imageType}"),
    ("get", "/Studios/{name}/Images/{imageType}/{imageIndex}"),
    ("head", "/Studios/{name}/Images/{imageType}/{imageIndex}"),
    ("post", "/SyncPlay/Buffering"),
    ("post", "/SyncPlay/Join"),
    ("post", "/SyncPlay/Leave"),
    ("get", "/SyncPlay/List"),
    ("post", "/SyncPlay/MovePlaylistItem"),
    ("post", "/SyncPlay/New"),
    ("post", "/SyncPlay/NextItem"),
    ("post", "/SyncPlay/Pause"),
    ("post", "/SyncPlay/Ping"),
    ("post", "/SyncPlay/PreviousItem"),
    ("post", "/SyncPlay/Queue"),
    ("post", "/SyncPlay/Ready"),
    ("post", "/SyncPlay/RemoveFromPlaylist"),
    ("post", "/SyncPlay/Seek"),
    ("post", "/SyncPlay/SetIgnoreWait"),
    ("post", "/SyncPlay/SetNewQueue"),
    ("post", "/SyncPlay/SetPlaylistItem"),
    ("post", "/SyncPlay/SetRepeatMode"),
    ("post", "/SyncPlay/SetShuffleMode"),
    ("post", "/SyncPlay/Stop"),
    ("post", "/SyncPlay/Unpause"),
    ("get", "/SyncPlay/{id}"),
    ("get", "/System/ActivityLog/Entries"),
    ("get", "/System/Configuration"),
    ("post", "/System/Configuration"),
    ("post", "/System/Configuration/Branding"),
    ("get", "/System/Configuration/MetadataOptions/Default"),
    ("get", "/System/Configuration/{key}"),
    ("post", "/System/Configuration/{key}"),
    ("get", "/System/Endpoint"),
    ("get", "/System/Info"),
    ("get", "/System/Info/Public"),
    ("get", "/System/Info/Storage"),
    ("get", "/System/Logs"),
    ("get", "/System/Logs/Log"),
    ("get", "/System/Ping"),
    ("post", "/System/Ping"),
    ("post", "/System/Restart"),
    ("post", "/System/Shutdown"),
    ("get", "/Tmdb/ClientConfiguration"),
    ("get", "/Trailers"),
    ("get", "/Trailers/{itemId}/Similar"),
    ("delete", "/UserFavoriteItems/{itemId}"),
    ("post", "/UserFavoriteItems/{itemId}"),
    ("delete", "/UserImage"),
    ("get", "/UserImage"),
    ("head", "/UserImage"),
    ("post", "/UserImage"),
    ("get", "/UserItems/Resume"),
    ("delete", "/UserItems/{itemId}/Rating"),
    ("post", "/UserItems/{itemId}/Rating"),
    ("get", "/UserItems/{itemId}/UserData"),
    ("post", "/UserItems/{itemId}/UserData"),
    ("delete", "/UserPlayedItems/{itemId}"),
    ("post", "/UserPlayedItems/{itemId}"),
    ("get", "/UserViews"),
    ("get", "/UserViews/GroupingOptions"),
    ("get", "/Users"),
    ("post", "/Users"),
    ("post", "/Users/AuthenticateByName"),
    ("post", "/Users/AuthenticateWithQuickConnect"),
    ("post", "/Users/Configuration"),
    ("post", "/Users/ForgotPassword"),
    ("post", "/Users/ForgotPassword/Pin"),
    ("get", "/Users/Me"),
    ("post", "/Users/New"),
    ("post", "/Users/Password"),
    ("get", "/Users/Public"),
    ("delete", "/Users/{userId}"),
    ("get", "/Users/{userId}"),
    ("post", "/Users/{userId}/Policy"),
    ("delete", "/Videos/ActiveEncodings"),
    ("post", "/Videos/MergeVersions"),
    ("get", "/Videos/{itemId}/AdditionalParts"),
    ("delete", "/Videos/{itemId}/AlternateSources"),
    ("post", "/Videos/{itemId}/Subtitles"),
    ("delete", "/Videos/{itemId}/Subtitles/{index}"),
    ("get", "/Videos/{itemId}/Trickplay/{width}/tiles.m3u8"),
    ("get", "/Videos/{itemId}/Trickplay/{width}/{index}.jpg"),
    ("get", "/Videos/{itemId}/hls/{playlistId}/stream.m3u8"),
    (
        "get",
        "/Videos/{itemId}/hls/{playlistId}/{segmentId}.{segmentContainer}",
    ),
    (
        "get",
        "/Videos/{itemId}/hls1/{playlistId}/{segmentId}.{container}",
    ),
    ("get", "/Videos/{itemId}/live.m3u8"),
    ("get", "/Videos/{itemId}/main.m3u8"),
    ("get", "/Videos/{itemId}/master.m3u8"),
    ("head", "/Videos/{itemId}/master.m3u8"),
    ("get", "/Videos/{itemId}/stream"),
    ("head", "/Videos/{itemId}/stream"),
    ("get", "/Videos/{itemId}/stream.{container}"),
    ("head", "/Videos/{itemId}/stream.{container}"),
    (
        "get",
        "/Videos/{itemId}/{mediaSourceId}/Subtitles/{index}/subtitles.m3u8",
    ),
    (
        "get",
        "/Videos/{routeItemId}/{routeMediaSourceId}/Subtitles/{routeIndex}/Stream.{routeFormat}",
    ),
    (
        "get",
        "/Videos/{routeItemId}/{routeMediaSourceId}/Subtitles/{routeIndex}/{routeStartPositionTicks}/Stream.{routeFormat}",
    ),
    (
        "get",
        "/Videos/{videoId}/{mediaSourceId}/Attachments/{index}",
    ),
    ("get", "/Years"),
    ("get", "/Years/{year}"),
    ("get", "/web/ConfigurationPage"),
    ("get", "/web/ConfigurationPages"),
];
