//! `TrickplayController` — scrubbing-preview playlists and tiles.
//!
//! Ports both of Jellyfin's `TrickplayController` routes:
//! - `GET /Videos/{itemId}/Trickplay/{width}/tiles.m3u8` — the HLS image-tiles
//!   playlist for a resolution (built from the stored trickplay metadata).
//! - `GET /Videos/{itemId}/Trickplay/{width}/{index}.jpg` — a single tile image
//!   file (served when present on disk).
//!
//! The route *template* collapses `{index}.jpg` to a single `{index}` capture
//! (axum allows one placeholder per segment); the captured value is still the
//! client's `0.jpg`, so the handler parses the index off it. The on-disk tile
//! path comes from the [`TrickplayManager`]; tiles are generated by the
//! "Generate Trickplay Images" task, so an item whose metadata exists but
//! whose tiles are absent yields `404` — matching the C# `File.Exists` gate.

use axum::Router;
use axum::extract::{Path, Query, Request, State};
use axum::http::header;
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use ferrofin_model::secret::Secret;
use uuid::Uuid;

use crate::auth::RequireAuth;
use crate::error::ApiError;
use crate::handlers::hls::parse_segment_index;
use crate::handlers::streaming::serve_static_file;
use crate::state::AppState;

/// Query parameters shared by the trickplay routes.
#[derive(Debug, Default, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct TrickplayQuery {
    /// Optional. The media version id, if using an alternate version.
    #[serde(
        default,
        deserialize_with = "crate::handlers::query_parse::empty_as_none_uuid"
    )]
    media_source_id: Option<Uuid>,
}

/// `GET /Videos/{itemId}/Trickplay/{width}/tiles.m3u8` — the tiles playlist.
///
/// Port of `TrickplayController.GetTrickplayHlsPlaylist`: builds the `.m3u8`
/// text for the resolution `width` (keyed on the `mediaSourceId` when supplied,
/// else the item id). Returns `404` when no trickplay metadata exists for that
/// resolution.
#[utoipa::path(
    get,
    path = "/Videos/{itemId}/Trickplay/{width}/tiles.m3u8",
    params(
        ("itemId" = String, Path, description = "The item id"),
        ("width" = i32, Path, description = "The width of a single tile"),
        ("mediaSourceId" = Option<String>, Query, description = "The media version id, if using an alternate version")
    ),
    responses(
        (status = 200, description = "Tiles playlist returned"),
        (status = 404, description = "Not found")
    ),
    tag = "ferrofin"
)]
async fn get_trickplay_hls_playlist(
    State(state): State<AppState>,
    RequireAuth(auth): RequireAuth,
    Path((item_id, width)): Path<(Uuid, i32)>,
    Query(query): Query<TrickplayQuery>,
) -> Result<Response, ApiError> {
    let source_id = query.media_source_id.unwrap_or(item_id);
    let playlist = state
        .trickplay
        .get_hls_playlist(source_id, width, auth.token.as_ref().map(Secret::expose))
        .await?;
    match playlist {
        Some(text) if !text.is_empty() => Ok((
            [(header::CONTENT_TYPE, "application/vnd.apple.mpegurl")],
            text,
        )
            .into_response()),
        _ => Err(ApiError::NotFound(format!(
            "no trickplay playlist for item {item_id} at width {width}"
        ))),
    }
}

/// `GET /Videos/{itemId}/Trickplay/{width}/{index}.jpg` — a tile image.
///
/// Port of `TrickplayController.GetTrickplayTileImage`: resolves the on-disk
/// tile path for the resolution + tile index (keyed on `mediaSourceId` when
/// supplied, else the item id) and serves the file with a
/// `Content-Disposition: attachment` header. Returns `404` when the resolution
/// is unknown or the tile file is absent.
///
/// The route template drops the trailing `.jpg` literal, but the captured
/// `index` is the whole segment (`0.jpg`), so it is parsed here; a
/// non-numeric value is `400`.
#[utoipa::path(
    get,
    path = "/Videos/{itemId}/Trickplay/{width}/{index}",
    params(
        ("itemId" = String, Path, description = "The item id"),
        ("width" = i32, Path, description = "The width of a single tile"),
        ("index" = String, Path, description = "The index of the desired tile (`{index}.jpg`)"),
        ("mediaSourceId" = Option<String>, Query, description = "The media version id, if using an alternate version")
    ),
    responses(
        (status = 200, description = "Tile image returned"),
        (status = 404, description = "Not found")
    ),
    tag = "ferrofin"
)]
async fn get_trickplay_tile_image(
    State(state): State<AppState>,
    RequireAuth(_auth): RequireAuth,
    Path((item_id, width, index)): Path<(Uuid, i32, String)>,
    Query(query): Query<TrickplayQuery>,
    request: Request,
) -> Result<Response, ApiError> {
    // The vendored route is `{index}.jpg`; axum captures the whole segment, so
    // the `.jpg` literal is parsed off here (as the HLS segment handlers do).
    let index = parse_segment_index(&index)?;
    let source_id = query.media_source_id.unwrap_or(item_id);
    let Some(path) = state
        .trickplay
        .get_trickplay_tile_path(source_id, width, index)
        .await?
    else {
        return Err(ApiError::NotFound(format!(
            "no trickplay tiles for item {item_id} at width {width}"
        )));
    };

    let mut response = serve_static_file(&path, request).await?;
    if let Ok(value) = header::HeaderValue::from_str("attachment") {
        response
            .headers_mut()
            .insert(header::CONTENT_DISPOSITION, value);
    }
    Ok(response)
}

/// Registers this controller's real routes onto `router`.
pub fn register(router: Router<AppState>) -> Router<AppState> {
    router
        .route(
            "/Videos/{itemId}/Trickplay/{width}/tiles.m3u8",
            get(get_trickplay_hls_playlist),
        )
        .route(
            "/Videos/{itemId}/Trickplay/{width}/{index}",
            get(get_trickplay_tile_image),
        )
}
